#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "deluge"
name = "Deluge"
description.en = "Lightweight BitTorrent client"
description.fr = "Client BitTorrent léger"

version = "2.0.3~ynh5"

maintainers = []

[upstream]
license = "GPL-3.0-or-later"
website = "https://www.deluge-torrent.org/"
admindoc = "https://deluge.readthedocs.io/en/latest/"
code = "https://git.deluge-torrent.org/deluge"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/deluge"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8112

    [resources.apt]
    packages = "deluge, deluged, deluge-console, deluge-web"
